# Generated by Django 3.2.2 on 2021-06-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneModelClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model_number', models.IntegerField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('battery', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('camera_front', models.CharField(max_length=50)),
                ('camera_back', models.CharField(max_length=50)),
                ('os_name', models.CharField(max_length=100)),
            ],
        ),
    ]
